### ISSUE TITLE
Set of temporary page questions. `https://temp.main.layerview.io/`

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#301] opened 2023-04-24 08:45 UTC
Click ▶️ to view details:
<details>
<summary>1、There is an anomaly in the occurrence of time in Latest Blocks.</summary>
Stay on the homepage for a period of time, during which blocks are generated more frequently. In Latest Blocks, the time of the previous block is not automatically updated when a new block comes out, and manually refreshing the page can be resolved.

Temporary environment https://temp.main.layerview.io/
<img width="452" alt="image" src="https://user-images.githubusercontent.com/25676576/233943340-4ac185e3-1603-4a99-aa4d-16be7aeb9da2.png">
</details>

<details>
<summary>2、Compared with the production line, the menu bar of the temporary main network has more Fee Rate, click it and the page will display 404.</summary>
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/25676576/233948902-ed39cd76-bd8b-4f99-b0b8-151cc888203c.png">
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/25676576/233949022-ae646a7b-6aa5-492c-9e10-e01002874d97.png">
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/25676576/233949803-f5e05318-8add-4531-8c1c-aa241542287c.png">
</details>

<details>
<summary>3、There are differences in the page information of the same block of data at the same time.</summary>
Block 0x2769c150f161a35426a52e19fb01a27b16cce1407eca9d66769450e4845da548
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/25676576/233952794-ec7419f0-3e6c-45ed-a264-dccbf9a303d9.png">
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/25676576/233953126-2c771262-f58d-4f77-b310-763702f51d6e.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/25676576/233953213-2f7d06e2-ede5-4188-a78e-9f1a0f5aad06.png">
<img width="520" alt="image" src="https://user-images.githubusercontent.com/25676576/233953550-317ef98f-8f69-47db-84ec-351cecff82f7.png">
</details>

<details>
<summary>4、Differences in the Miner address page.</summary>
Miner address: ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvzz8cmjw9pqlx48d3s9nr49fhu89jk8rgycece5
4-1
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/25676576/233956689-c8b2d81e-bb78-4d8e-b57e-63fc9940de05.png">
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/25676576/233956841-124b7839-65ea-4cf5-95c0-8d8fbd4a4999.png">
4-2
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/25676576/233961426-4168f695-98d7-4863-895d-9db7d924af02.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/25676576/233961296-e32d7ee2-c4d3-4c02-862b-0b66b86a5e33.png">
4-3
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/25676576/233957908-54524ae2-4abf-4cfa-b7cb-eeaf05630990.png">
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/25676576/233957836-c7efb8f2-cdbe-4832-bda7-fed38ec4361f.png">
4-4
Viewing in the deprecated address format also has the same differences as above.

https://temp.main.layerview.io/address/ckb1qyqgyy03hyu2zp7d2wmrqtx822n0cwt9vwxsqn2n93
https://explorer.nervos.org/address/ckb1qyqgyy03hyu2zp7d2wmrqtx822n0cwt9vwxsqn2n93

</details>

<details>
<summary>5、There is an exception on the same transaction page at the same time.</summary>
Transaction 0x5a63416b4e5b736fc09f8ba3bdc84a1b0fc95ebc55e9f86e9fefc86b99bf65de
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/25676576/233967257-1603d97d-6994-4c86-8809-494589616797.png">
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/25676576/233967122-0c45b1ef-9cc0-4e06-a7f9-20e8a4e9e4f8.png">
</details>

<details>
<summary>6、If the same data structure is used, pending transactions should be consistent. Now the two are different. When the temp data is consistent, it is 256, and there is no change.</summary>
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/25676576/233997205-ff27478c-6c7e-4b67-9179-f022f78292a0.png">
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/25676576/233997408-16d92106-8034-4493-bffa-99f5b9f4fd7c.png">
</details>

<details>
<summary>7、Production line data cannot be searched on temp.</summary>
Transaction 0x21e7843a6c5d9ccda744a8cc0e34f8e3b432b15537c04687ee7a7c8e4c0f4264

https://temp.main.layerview.io/search/fail?q=0x21e7843a6c5d9ccda744a8cc0e34f8e3b432b15537c04687ee7a7c8e4c0f4264
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/25676576/234005456-536850ec-0bcf-439d-8f9e-e5e9116ef2d0.png">
</details>

<details>
<summary>8、The statistical data of the NervosDao page in the screenshot, except for the red frame, the data are different.</summary>
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/25676576/234011821-e094a45a-8d20-4cf3-b5f0-925f20b14485.png">
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/25676576/234011950-dfe230b3-24c6-4439-83a9-676002411319.png">
</details>

<details>
<summary>9、Compared with the production line with the same data, the detailed data on temp is missing. But modifying the parameter page=3 or page=4 in the url can get the last 2 pages of data.</summary>

https://temp.main.layerview.io/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2h8d5ckf6qa5p6uenq9qne5gulkfyn54sj9s54f?page=1

Another set of data (https://temp.main.layerview.io/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcq2mxh9ylwpuqr9gyykcct2r788ua7wfqnsexjwte?page=4)
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/25676576/234019640-411d636b-a805-4a07-b3e3-532a67aa2fbc.png">
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/25676576/234020811-0b7b3ec4-3334-445c-ac04-eacd506f00f3.png">
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/25676576/234022496-e3eec853-31ec-41f0-8c9b-cafa4d06fd47.png">
</details>

<details>
<summary>10、The first data of temp and production line on the NFT Collection page are different.</summary>

https://temp.main.layerview.io/nft-collections
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/25676576/234171128-2e26cc53-b1ef-4391-91c3-869b1a935c9f.png">
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/25676576/234171171-5afcb171-73a2-47c7-b203-7cf62dfafa86.png">
</details>

<details>
<summary>11、I downloaded the file of Block Time Distribution (Recent 50000 blocks), and found that there are differences in the data in the middle.</summary>

[出块时间分布 (temp).csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11321193/temp.csv)
[出块时间分布.csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11321195/default.csv)
</details>

<details>
<summary>12、For the data downloaded from the Difficulty page, temp has one more data than the production line.</summary>

[difficulty(temp).csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11321817/difficulty.temp.csv) 1252
[难度.csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11321829/default.csv) 1251
</details>

<details>
<summary>13、The last few pieces of data downloaded from the Hash Rate（uncle-rate） page are inconsistent.</summary>
<img width="371" alt="image" src="https://user-images.githubusercontent.com/25676576/234263885-643e0a57-96f0-4d8a-ac42-b55203d3eb4f.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/25676576/234263731-fb5379e6-55b9-4746-91dc-aa035bfb2799.png">

[哈希率(temp).csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11322036/temp.csv)
[哈希率.csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11322040/default.csv)

<img width="406" alt="image" src="https://user-images.githubusercontent.com/25676576/234265948-f0d5dec7-0bed-41cc-ac34-c53ff7e111a7.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/25676576/234266042-28cf43cc-4c7f-4c5a-b458-d4d031b1a576.png">

[uncle-rate(temp).csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11322107/uncle-rate.temp.csv)
[uncle-rate.csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11322109/uncle-rate.csv)
</details>

<details>
<summary>14、The data in the Top Miners (Recent 7 days) page is inconsistent.</summary>
<img width="818" alt="image" src="https://user-images.githubusercontent.com/25676576/234267507-b154df6b-54c2-4e25-b0b2-5e03b342c27f.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/25676576/234267561-428c299e-4d37-42bd-b477-46fe9eb0d452.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/25676576/234267403-cd185794-7544-470d-a32c-7c9f71a1ac56.png">
<img width="269" alt="image" src="https://user-images.githubusercontent.com/25676576/234267618-4708fbce-1980-4d54-9318-06c677e6defd.png">

[top-miners(temp).csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11322150/top-miners.temp.csv)
[top-miners.csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11322153/top-miners.csv)
</details>

<details>
<summary>15、The data in the Miner Versions (Recent 7 days) page is inconsistent.</summary>
<img width="905" alt="image" src="https://user-images.githubusercontent.com/25676576/234270353-680346c8-6772-447e-a703-9ee81be2a6a4.png">
<img width="981" alt="image" src="https://user-images.githubusercontent.com/25676576/234270404-8de1e8e4-50f9-46f4-9489-9b3888adc0d2.png">
</details>

<details>
<summary>16、The last few pieces of data downloaded from the Transaction Count  page are inconsistent.</summary>
<img width="279" alt="image" src="https://user-images.githubusercontent.com/25676576/234271701-fae9da24-3bf9-4026-a818-710a2e298e18.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/25676576/234271874-1f14c1e5-706e-4505-8a53-72a61d24fda0.png">

[transaction-count(temp).csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11322333/transaction-count.temp.csv)
[transaction-count.csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/11322334/transaction-count.csv)

Similar questions on other pages:
16-1 Unique Addresses Used
<img width="256" alt="image" src="https://user-images.githubusercontent.com/25676576/234273896-6a6ec896-d498-4f35-a3c2-097297eeb1ff.png">
<img width="210" alt="image" src="https://user-images.githubusercontent.com/25676576/234273949-382629fc-d4c6-41db-957b-8773c8d2f757.png">

16-2 Cell Count
<img width="300" alt="image" src="https://user-images.githubusercontent.com/25676576/234274329-12ee3550-82c2-4565-aa7a-34cf8f902381.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/25676576/234274406-d5d5dad8-9f17-4c09-ad98-a4e0963a1bb2.png">
</details>

<details>
<summary>17、There are 5 data inconsistencies in the downloaded data of Balance Ranking.</summary>

https://temp.main.layerview.io/charts/address-balance-rank
<img width="267" alt="image" src="https://user-images.githubusercontent.com/25676576/234275300-2928b447-1eb5-4d28-9d48-2afa132bacd0.png">
<img width="233" alt="image" src="https://user-images.githubusercontent.com/25676576/234275469-e550c387-ef65-4c41-a56e-9b790026ad1f.png">

Similar questions on other pages:
17-1 There are only slight differences in the download data of Balance Distribution.
https://temp.main.layerview.io/charts/balance-distribution
<img width="327" alt="image" src="https://user-images.githubusercontent.com/25676576/234276602-cb249ba9-64f9-4f9d-b99f-2a63bc94554c.png">
<img width="286" alt="image" src="https://user-images.githubusercontent.com/25676576/234276650-22865662-35da-4ca0-ac1b-d3e7aa782083.png">

17-2 The last few sets of data downloaded from Transaction Fee are inconsistent.
https://temp.main.layerview.io/charts/tx-fee-history
<img width="245" alt="image" src="https://user-images.githubusercontent.com/25676576/234277418-edfc27e6-e45f-442f-bb28-dff6c998c6d6.png">
<img width="208" alt="image" src="https://user-images.githubusercontent.com/25676576/234277609-513c3342-1ffc-4877-a98a-53774f934805.png">

17-3 The last few sets of data downloaded from Total Nervos DAO Deposit & Accrued Total Depositors are inconsistent.
https://temp.main.layerview.io/charts/total-dao-deposit
<img width="316" alt="image" src="https://user-images.githubusercontent.com/25676576/234305328-a3740cf7-aec3-42b9-8d28-f13e42e88e1e.png">
<img width="281" alt="image" src="https://user-images.githubusercontent.com/25676576/234305446-22020abd-f3c4-4813-a046-36228955337c.png">

17-4 The last few sets of data downloaded from Daily Nervos DAO Deposit are inconsistent.
https://temp.main.layerview.io/charts/new-dao-deposit
<img width="286" alt="image" src="https://user-images.githubusercontent.com/25676576/234306583-751c4fd4-8ea7-4098-b076-d69b37b58a6d.png">
<img width="269" alt="image" src="https://user-images.githubusercontent.com/25676576/234306706-e2804ef6-eab4-410a-b842-686f2e43a6e8.png">

17-5 The last few sets of data downloaded from Deposit to Circulation Ratio are inconsistent.
https://temp.main.layerview.io/charts/circulation-ratio
<img width="223" alt="image" src="https://user-images.githubusercontent.com/25676576/234307492-5d3ef6d0-1e1c-4228-97c9-6837d0249926.png">
<img width="216" alt="image" src="https://user-images.githubusercontent.com/25676576/234307610-9f447646-8aef-453d-b247-8ced0ddcbe7e.png">

17-6 The last few sets of data downloaded from Total Supply are inconsistent.
https://temp.main.layerview.io/charts/total-supply
<img width="421" alt="image" src="https://user-images.githubusercontent.com/25676576/234308889-52a184cd-b8de-4726-828e-28783a419dfd.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/25676576/234308987-b1412872-1b7e-45b5-89cc-6f87a747d250.png">

17-7 The last few sets of data downloaded from Secondary Issuance are inconsistent.
https://temp.main.layerview.io/charts/secondary-issuance
<img width="347" alt="image" src="https://user-images.githubusercontent.com/25676576/234310087-fab83b74-dfbd-4482-b0e1-0c851e0b0236.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/25676576/234310141-f095e95f-94c2-4505-9862-752221487fea.png">

17-8 The last few sets of data downloaded from Liquidity are inconsistent.
https://temp.main.layerview.io/charts/liquidity
<img width="382" alt="image" src="https://user-images.githubusercontent.com/25676576/234311212-36bedea3-eb34-4593-bf2f-a8c8fa2a7378.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/25676576/234311310-74632c69-51f8-47c8-9bf5-686dc42c9ce9.png">

</details>

**Comment by FrederLu** [comment] 2023-04-26 02:27
@ShiningRay @Keith-CY
By comparing the data of `https://temp.main.layerview.io/` and `https://explorer.nervos.org/`, some data inconsistencies were found, and there was also a problem with the front-end style. Please confirm.
If there are problems found in the follow-up, we will continue to improve the issue here.

**Comment by FrederLu** [comment] 2023-04-26 06:26
@ShiningRay @Keith-CY Here is an additional question：
https://temp.main.layerview.io/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type/deployed_cells?page=1&size=10
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/25676576/234486196-c4515f6d-3397-42f0-a895-256ad34f97ad.png">
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/25676576/234486501-69e5b001-470c-4593-82b9-8af2dc08f4b8.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/25676576/234487230-e275bca0-5d18-4089-9614-fb42e82bf0cd.png">
<img width="643" alt="image" src="https://user-images.githubusercontent.com/25676576/234487676-96329e90-d3d1-4fa5-9c5a-c0e7d9afff8d.png">

**Comment by FrederLu** [comment] 2023-04-28 08:30
>2、Compared with the production line, the menu bar of the temporary main network has more Fee Rate, click it and the page will display 404.

The function has been updated, the intermediate data uses different nodes and the data on `mainnet` is slightly different, but it belongs to the normal category. Verification passed.

>3、There are differences in the page information of the same block of data at the same time.
>4、Differences in the Miner address page.
>7、Production line data cannot be searched on temp.

Verified.

**Comment by FrederLu** [comment] 2023-05-04 10:16
@ShiningRay @Keith-CY 
The previous questions were verified again. In addition to the [verified questions](https://github.com/Magickbase/ckb-explorer-public-issues/issues/301#issuecomment-1527186847), the failed questions are listed below.


>>1、There is an anomaly in the occurrence of time in Latest Blocks.
>is an issue of UI and is tracked by https://github.com/Magickbase/ckb-explorer-public-issues/issues/290

The problem still exists on temp.

>5、There is an exception on the same transaction page at the same time.

The problem still exists on the temp page, and the output data is more different than before.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/25676576/236132548-4782f139-ccae-4173-8d58-732d22132d73.png">
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/25676576/236133075-36493b14-e3a6-4149-b7e5-2142a0640b1a.png">

>8、The statistical data of the NervosDao page in the screenshot, except for the red frame, the data are different.

Compared with the previous data, the data this time has certain corrections. However, the nuclear opponent can see from the screenshots that there are still differences in the data marked in red.
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/25676576/236137149-be0a9502-df27-4895-a416-fcb22360d2a5.png">
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/25676576/236137083-6ecb5508-8850-446c-a8d8-8ddad3136277.png">

>9、Compared with the production line with the same data, the detailed data on temp is missing. But modifying the parameter page=3 or page=4 in the url can get the last 2 pages of data.

This problem still exists, and it is found that it is also abnormal on mainnet now.
https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2h8d5ckf6qa5p6uenq9qne5gulkfyn54sj9s54f?page=1

>11、I downloaded the file of Block Time Distribution (Recent 50000 blocks), and found that there are differences in the data in the middle.

Compared with the data in the downloaded file, the difference still exists.
https://temp.main.layerview.io/charts/block-time-distribution

>12、For the data downloaded from the Difficulty page, temp has one more data than the production line.

Now the amount of data is matched to 1265 pieces of data, but there is a difference in the information of the last piece of data. If the data source used is the same, there should be no difference with other information.
https://temp.main.layerview.io/charts/difficulty
<img width="208" alt="image" src="https://user-images.githubusercontent.com/25676576/236150002-2e66de29-2933-42fb-8f20-16348b1e0bf8.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/25676576/236150148-859b425f-5d39-46d0-bfc6-ae58ef0fb02c.png">

>13、The last few pieces of data downloaded from the Hash Rate（uncle-rate） page are inconsistent.

Now the amount of data is matched to 1265 pieces of data, but there is a difference in the information of the last piece of data.
https://temp.main.layerview.io/charts/hash-rate 

>14、The data in the Top Miners (Recent 7 days) page is inconsistent.

Now the amount of data is consistent, but there are still differences in individual data.
https://temp.main.layerview.io/charts/miner-address-distribution
<img width="160" alt="image" src="https://user-images.githubusercontent.com/25676576/236163781-e428b19b-57fe-4cc3-a73c-18bcf0008d44.png">
<img width="166" alt="image" src="https://user-images.githubusercontent.com/25676576/236164095-d1ba1e8a-b972-430a-b54a-2777a4102572.png">

>16、The last few pieces of data downloaded from the Transaction Count page are inconsistent.

(Same problem as 12) Now the amount of data is consistent, but there is still a difference in the last piece of data.

>17、There are 5 data inconsistencies in the downloaded data of Balance Ranking.

Except that the 17-5 data is consistent, the last item of other data is different.

The problem with the first point here still exists.
https://github.com/Magickbase/ckb-explorer-public-issues/issues/301#issuecomment-1522855014

**Comment by ShiningRay** [comment] 2023-05-08 00:39
14  is correct. The difference of each version of Top Miners is caused by caching.
The cache is built when page is requested. The access time of two pages may be different.
And the difference disappeared after I cleaned and rebuilt both caches.

**Comment by ShiningRay** [comment] 2023-05-08 01:22
I suggest to ignore problem#17 because we found there are some bugs in balance processing.
The difference is very tiny.
And these two charts are "snapshot" will be fixed easily after we fix the balance processing problems.

**Comment by ShiningRay** [comment] 2023-05-08 01:27
I cannot find difference in problem#16

**Comment by ShiningRay** [comment] 2023-05-08 01:59
In problem#16 the data in temp env is correct.

**Comment by FrederLu** [comment] 2023-05-08 08:52
The verified question has been updated.
https://github.com/Magickbase/ckb-explorer-public-issues/issues/301#issuecomment-1527186847
Listings that have not yet been verified. (verified with strikethrough)
https://github.com/Magickbase/ckb-explorer-public-issues/issues/301#issuecomment-1534481619

**Comment by FrederLu** [comment] 2023-06-05 09:28
Verified.

**Closed** 2023-06-06 07:11 UTC
Labels: bug
