### ISSUE TITLE
Update banner

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#175] opened 2023-01-28 07:35 UTC
UI design was updated in https://github.com/Magickbase/visual-style-guide/issues/22, the demo was incomplete because it's hard to be expressed by design tools, so a complementary description was added.

Feel free to confirm details in this issue

**Comment by WhiteMinds** [comment] 2023-01-28 10:04
This could be a more challenging task without the suitable library, so I started by assigning longer expected dates.
Now the research begins.

**Comment by WhiteMinds** [comment] 2023-01-29 15:05
由于内容较多，我可能无法使用英文完全表达我的意思，所以这里使用中文进行记录。

我下午和 @Kirl70 进行了沟通，在这里记录一些可能有用的信息：
1. 设计稿的动画是使用 Spline 制作的，该在线设计工具支持分享项目 （https://app.spline.design/file/fa01c1c0-f273-446b-a65f-3482dcfef006） 与导出代码。
不过实际导出的结果看起来性能很差，在我的机器上约 10 fps 左右并且占用极大的计算资源。
2. 涟漪的效果实现方式可以改为 3d 上的长方体变化，而不是类似滤镜叠加的效果。整体的开发实现上允许一些自由度。

一些想法和调研得到的一些信息：
1. 这个组件是位于首页的，所以需要最优先考虑的是性能问题，因为首屏的性能可以通过推迟渲染时机或其他懒加载方案来规避，所以主要考虑实时渲染时的性能。
2. 由于设计的效果上存在光照，这很难用 css 实现，所以将只调研 webGL 方向。
如果后续我们使用 webGL 实现了动画效果但发现仍然有性能上的影响，到时候可以考虑去掉光照然后换 js + css 的实现。
3. 在沟通前，看了一些滤镜叠加实现涟漪的相关资料，目前已经不需要了，不过在这里先留档
https://github.com/zhengsk/ImageFilters.js#examples
http://www.arahaya.com/imagefilters/ripple/
https://codepen.io/ppsirius/pen/dZmxRE
4. Spline 导出的项目很简单，主要是用了它们的 @splinetool/runtime 库以及一个封装的 splinecode 格式的 `scene.splinecode` 文件，这个库和文件格式看起来都是闭源的。
虽然库没有直接依赖 three.js，但是从库的开发依赖项以及其他的一些地方来看较大概率是基于 three.js 二次开发的。
从其他的 Spline 演示项目来看，它的性能应该没有差到这种程度，所以我想调查这个项目性能差的原因，但是这两个闭源给我带来了一些困难。所以暂时没有继续调查性能差的原因，不过之后可以参考 https://docs.spline.design/f6351697797e4e41bbf57d62ab905a06 优化看看。
5. 我查看了 https://github.com/Magickbase/visual-style-guide/issues/22#issuecomment-1407319332 中的 echarts-gl 案例，对这个库进行了一些调研。
它在 API 层面上有一些局限性，无法实现稍微复杂一点的柱子样式（比如设计稿上的文字柱子）、无法实现上浮方块等。
在更新 data 时（调整某些柱子高度）的效果不好，像是进行了一次 reset 一样。
从 http://pissang.github.io/dota2hero/#/hero/kunkka 体验来看，底层使用的渲染库 claygl 的性能应该没什么问题。
根据 https://github.com/pissang/claygl/issues/2 的说法，claygl 的性能和 three.js 差距不大，这也侧面证明 Spline 导出的动画卡顿应该不是渲染引擎层面的原因。
6. 由于 echarts-gl API 的问题，我打算尝试阅读它的源码层面是如何实现的，然后看看能不能复刻后进行调整。
相关的代码主要集中在 https://github.com/ecomfe/echarts-gl/blob/a3cb1c6bf0f64bed9c8ca144096689defb8e1ce3/src/chart/bar3D/Bar3DView.js 和 https://github.com/ecomfe/echarts-gl/blob/a3cb1c6bf0f64bed9c8ca144096689defb8e1ce3/src/util/geometry/Bars3DGeometry.js。
这里面涉及了较多的 webGL 知识，这是我没有了解过的，考虑到后续的开发中可能会遇到更多相关问题，我的打算是明天先系统性的学习一些 webGL 知识，然后再继续调研。

**Comment by Keith-CY** [comment] 2023-01-29 18:45
Library https://github.com/protectwise/troika could help

**Comment by Keith-CY** [comment] 2023-02-03 09:04
How is it going

**Comment by WhiteMinds** [comment] 2023-02-03 10:25
> How is it going

It took me two days to getting started with webGL, and then I started investigating the cause of Spline animation render with very low frame count, and found that the problem was mainly in the glass property of the cube material, and that if I removed this property it would render with normal frame count.

By design, the glass property is used to achieve the glassy feel of the cube and to diffuse the internal and external light.

I was going to try to see if there was another way to achieve a similar effect, but in the first step, developing with Spline's libraries(like `@splinetool/runtime`), I realized that they didn't seem developer-friendly enough, the API was less free, and the libraries and the `splinecode` file format they use where closed-source.

This is bad for our subsequent development and maintenance, because Spline encloses(or blocks? 封闭) the stuff made with it within its ecology, but its ecology is not yet rich enough.

So I decided to abandon Spline and use the threejs implementation instead.

I tried to reuse what was already implemented on Spline before I started, but its exported gltf format is missing materials, and exporting materials requires a membership, so for now it's a complete reimplementation.

The progress of the implementation is still in the research stage. From the research, the cube ripple effect, replacing the cube by text and other aspects should not encounter too many problems.

The issue being researched right now is the incorrect camera angle and text placement, this should be a minor issue but has taken me an hour and it looks like I'm not getting to the point yet, but I shouldn't be stuck for long.

**Comment by Keith-CY** [comment] 2023-02-03 10:38
> > How is it going
> 
> It took me two days to getting started with webGL, and then I started investigating the cause of Spline animation render with very low frame count, and found that the problem was mainly in the glass property of the cube material, and that if I removed this property it would render with normal frame count.
> 
> By design, the glass property is used to achieve the glassy feel of the cube and to diffuse the internal and external light.
> 
> I was going to try to see if there was another way to achieve a similar effect, but in the first step, developing with Spline's libraries(like `@splinetool/runtime`), I realized that they didn't seem developer-friendly enough, the API was less free, and the libraries and the `splinecode` file format they use where closed-source.
> 
> This is bad for our subsequent development and maintenance, because Spline encloses(or blocks? 封闭) the stuff made with it within its ecology, but its ecology is not yet rich enough.
> 
> So I decided to abandon Spline and use the threejs implementation instead.
> 
> I tried to reuse what was already implemented on Spline before I started, but its exported gltf format is missing materials, and exporting materials requires a membership, so for now it's a complete reimplementation.
> 
> The progress of the implementation is still in the research stage. From the research, the cube ripple effect, replacing the cube by text and other aspects should not encounter too many problems.
> 
> The issue being researched right now is the incorrect camera angle and text placement, this should be a minor issue but has taken me an hour and it looks like I'm not getting to the point yet, but I shouldn't be stuck for long.

That's cool, looking forward to the final effect.

**Comment by WhiteMinds** [comment] 2023-02-06 10:22
https://user-images.githubusercontent.com/9160743/216944904-aa03030c-d6c0-446b-a169-ae40eb32a462.mp4

This is a demo currently implemented using threejs, which verifies the feasibility of the overall implementation.

There are still many problems hidden in the demo. I will continue to processing in the past two days. If a certain problem is difficult to progress for a period of time, I will report here again.

**Comment by Keith-CY** [comment] 2023-02-06 11:02
> Kapture.2023-02-06.at.18.10.45.mp4 
> This is a demo currently implemented using threejs, which verifies the feasibility of the overall implementation.
> 
> There are still many problems hidden in the demo. I will continue to processing in the past two days. If a certain problem is difficult to progress for a period of time, I will report here again.

This is so cool! We're almost there.

There're some details I'd like to adjust by a transverse section

At first
```
         ■■■■
         ■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
```


New block comes and `CKB` up
```
         ■■■■
         ■■■■
         ■■■■
         ■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
```

Ripple starts
```
         ■■■■
         ■■■■
       ■■■■■■■■
       ■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
```

`CKB` down, and ripple expands
```
   ■■    ■■■■    ■■
   ■■    ■■■■    ■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
```


```
 ■■      ■■■■      ■■
 ■■      ■■■■      ■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
```

Ripple down, with one `pillar` up, indicates that there's one transaction in the block 
```
         ■■■■      ■■
         ■■■■      ■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■
```

I'm not sure if it's clear enough, feel free to ask more

**Comment by WhiteMinds** [comment] 2023-02-06 14:54
> I'm not sure if it's clear enough, feel free to ask more

I think I get it.

**Comment by WhiteMinds** [comment] 2023-02-09 05:21
At present, there are some problems that cannot be solved quickly. We need to use some temporary solutions first, and then iterate slowly after going online. They are listed below:
1. Now the width of canvas is fixed, if it is changed, the picture will be stretched and the camera shooting angle will be incorrect. This should be because the camera parameters need to be dynamically calculated and set, dealing with this problem requires further study of relevant knowledge points.
The current temporary solution is to fix a width and leave blank space on the left and right sides of the canvas.
1. The display effect of the font dot matrix obtained through canvas is too thick, so a custom font dot matrix collection is required.
The current temporary solution is to only support the `C K B`.
1. The design draft style of the text cube is difficult to achieve, and ShaderMaterial may be required. To deal with this problem, further study of shader, glsl, etc. is required.
The current temporary solution is to directly use the style of MeshNormalMaterial as an alternative.

For problem 1, there are two ways to leave blank space:
1. no truncation effect
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/9160743/217723152-2572a8c6-f218-4173-96ef-d0f74dd5a0b2.png">
2. truncation effect
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/9160743/217723167-f259d7da-c2ae-4d48-9edc-85a9398daf91.png">

But neither looks good, any thoughts @Kirl70 @Keith-CY ?

If the effect of the temporary solution of fixed width + blank space is unacceptable, wait for the dynamic calculation of camera parameters to be processed before going online.

**Comment by Kirl70** [comment] 2023-02-09 06:33
> But neither looks good, any thoughts @Kirl70 @Keith-CY ?
> 
> If the effect of the temporary solution of fixed width + blank space is unacceptable, wait for the dynamic calculation of camera parameters to be processed before going online.

An idea, the bottom square needs to be spread all over the fixed canvas, and the left and right sides of the canvas use a gradient transparency effect as a mask, so that it does not look like a sudden cut-off effect. Example of the effect:
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/106060898/217735559-dc8f7722-201d-4756-9353-dc3b7a00a62d.png">

**Comment by Keith-CY** [comment] 2023-02-13 02:48
How is it going

**Comment by WhiteMinds** [comment] 2023-02-13 04:02
> How is it going

I'm working on the refactor code for the PR I'm going to submit

**Comment by WhiteMinds** [comment] 2023-02-13 07:13
PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1201

The effects of the design draft not achieved in this PR are as follows:
1. The style of the text cube
2. Adaptive render area width

**Comment by WhiteMinds** [comment] 2023-02-13 07:30
Current effect

https://user-images.githubusercontent.com/9160743/218396745-dd80e5b4-678e-4194-a3e8-c649d23fa104.mp4

**Comment by Keith-CY** [comment] 2023-02-13 17:07
> PR: [nervosnetwork/ckb-explorer-frontend#1201](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1201)
> 
> The effects of the design draft not achieved in this PR are as follows:
> 
> 1. The style of the text cube (now use MeshNormalMaterial default style)
> 2. Adaptive render area width (now fixed width)
> 
> And do not support any text, now only support `CKB`.

For point 1, if it's hard to enable texture as the design specified, we can change the design based on what is available now.

**Comment by WhiteMinds** [comment] 2023-02-14 06:54
> For point 1, if it's hard to enable texture as the design specified, we can change the design based on what is available now.

I think this is a result of my lack of expertise in webGL, rather than the problem itself being more difficult and looking for a developer with that skill to submit improvements that fit the design.

I actually have some idea about the specific implementation, but it will take a long time, so I did not continue.

**Comment by WhiteMinds** [comment] 2023-02-17 12:23
After communication with the @Keith-CY @Kirl70 , the animation effect to be launched this time is basically decided to be the effect of the following video:

https://user-images.githubusercontent.com/9160743/219650321-99976e76-73ad-4691-a25f-c7179b62bc7e.mp4

There are currently two performance issues, both of which have been briefly bypass in the video to make them look smooth, but will need to continue to be fixed and refactored before they are incorporated into the repository:
1. Calling `dispatch` anywhere (e.g. interval request, timer) will cause a lot of components to render, consuming about 40ms, causing the animation to drop frames and lag significantly, requiring a refactoring of the code.
1. There is a problem with the implementation of the animated scene itself, both the normal cubes and the text cubes need to be refactor into an `InstancedMesh` implementation, otherwise it takes about 30ms to draw one frame, i.e. fps=30.

**Comment by WhiteMinds** [comment] 2023-02-20 06:42
> There is a problem with the implementation of the animated scene itself, both the normal cubes and the text cubes need to be refactor into an InstancedMesh implementation, otherwise it takes about 30ms to draw one frame, i.e. fps=30.

The refactoring of the rendering implementation for each frame of the animation has been submitted to this PR https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1220

**Comment by WhiteMinds** [comment] 2023-02-20 11:31
> The refactoring of the rendering implementation for each frame of the animation has been submitted to this PR [nervosnetwork/ckb-explorer-frontend#1220](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1220)

A commit for optimizing the rendering performance of the components in the home page has also been added to this PR.

**Closed** 2023-05-08 07:20 UTC
Labels: enhancement
