### ISSUE TITLE
Change some indexes to hash index

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#74] opened 2022-10-08 03:42 UTC
Please list all the columns below:

**Comment by Keith-CY** [comment] 2022-10-08 05:50
Seems the issue is not complete, should someone else be assigned to add details?

**Comment by iamyates** [comment] 2022-10-09 01:44
I collected all the database index and listed it here: 

https://www.notion.so/4327787f09c44ff5b7c54bc9b388a719?v=7681bfed7e284c0aa026e41ac700ed18

![image](https://user-images.githubusercontent.com/105087155/194733662-f8696a24-705e-4c02-b98d-cb552b1c25a0.png)

**Comment by iamyates** [comment] 2022-10-09 01:48
> Seems the issue is not complete, should someone else be assigned to add details?

please assign this issue to me~

**Comment by iamyates** [comment] 2022-10-09 01:48
haha , OK I assigned this issue to myself.

**Comment by Keith-CY** [comment] 2022-10-09 05:24
> I collected all the database index and listed it here:
> 
> [notion.so/4327787f09c44ff5b7c54bc9b388a719?v=7681bfed7e284c0aa026e41ac700ed18](https://www.notion.so/4327787f09c44ff5b7c54bc9b388a719?v=7681bfed7e284c0aa026e41ac700ed18)
> 
> ![image](https://user-images.githubusercontent.com/105087155/194733662-f8696a24-705e-4c02-b98d-cb552b1c25a0.png)

The doc is private, could you post the data in this issue, or make the page public?

**Comment by iamyates** [comment] 2022-10-09 06:34
Sure, I made this doc public, please visit: https://rustic-soil-9c7.notion.site/4327787f09c44ff5b7c54bc9b388a719?v=7681bfed7e284c0aa026e41ac700ed18   

also I sent you an invitation of notion.  




> > I collected all the database index and listed it here:
> > [notion.so/4327787f09c44ff5b7c54bc9b388a719?v=7681bfed7e284c0aa026e41ac700ed18](https://www.notion.so/4327787f09c44ff5b7c54bc9b388a719?v=7681bfed7e284c0aa026e41ac700ed18)
> > ![image](https://user-images.githubusercontent.com/105087155/194733662-f8696a24-705e-4c02-b98d-cb552b1c25a0.png)
> 
> The doc is private, could you post the data in this issue, or make the page public?

**Comment by iamyates** [comment] 2022-10-09 09:42
![8841ae95e00e81677e7ac8979e18cec](https://user-images.githubusercontent.com/105087155/194749594-fcf14bea-ffc7-4c5f-a374-8fd1c46a8001.jpg)

When query big tables ( such as blocks which has 8+ million records, query by block_hash) , 
- when using `btree` index, the `execute time` is between 0.03~0.05ms
- after switching to `hash` index, the `execute time` reduced to 0.01~0.03ms

(the data comes from my PC. I think it may perform better in production server)

**Comment by iamyates** [comment] 2022-10-10 09:44
related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1025

**Closed** 2023-11-23 07:03 UTC
Labels: documentation
