### ISSUE TITLE
Faucet page style issue.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#343] opened 2023-06-12 07:40 UTC
1、Comparing the before and after screenshots, when a prompt appears below the address, it will cause the displacement of `Claim`.

<img width="1102" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/f55ad57d-4328-44d8-b04f-05f5df58a74a">
<img width="1100" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/4a50ea50-8bb3-4128-9bb4-bc303835da6a">
<img width="1124" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e0f06a99-79b2-46b2-a3d2-1215fa340e77">

---
2、After clicking `Remaining` multiple times on the mobile terminal? icon, the prompt information cannot be seen.
<img width="313" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/92687a4e-e697-4544-a5ad-36e18f029dca">
<img width="300" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/70a063a1-cf1e-4a0c-add0-4728b6d37f52">

**Comment by Kirl70** [comment] 2023-06-13 02:39
1、Buttons are not centered
<img width="1008" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/eb076bfd-ed10-496b-95da-f890b4cc9924">

2、Spacing does not match the design
<img width="1399" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/2076d70f-ca56-457a-bbe0-8089fe63bf94">

Design Draft:
<img width="594" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/6ce73c5e-9025-45e1-bb3a-e55956762d72">

**Comment by IronLu233** [comment] 2023-06-13 03:11
@Kirl70 Seems the website is slate. Please visit https://ckb-testnet-faucet-frontend-eu5fytq14-magickbase.vercel.app/ for verification
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/20639676/a7086a2c-9ccb-4c9a-8ea4-30335d862b8c)

**Comment by IronLu233** [comment] 2023-06-14 07:40
The button centered bug have been fixed by https://github.com/Magickbase/ckb-testnet-faucet-frontend/pull/5 .
And the other two issue of style is not a bug, caused by cache in designer's device.

**Closed** 2023-06-19 02:43 UTC
Labels: bug
