### ISSUE TITLE
The style of the testnet transaction details page is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#411] opened 2023-08-23 01:47 UTC
Duplicate abnormal data appears on the transaction details page.
https://pudge.explorer.nervos.org/transaction/0xaf6690becc7e7f6981322cc73f5d3834728789de194888de3e560290c38cbc7e
<img width="1187" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/dccb461c-2b9f-49b6-b1eb-2a18382da8cc">

<img width="1293" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a00b5a99-4531-4440-80bb-813418712e70">

**Comment by zhangyouxin** [comment] 2023-08-23 01:54
Didn't reproduce, is there more details about this issue?
<img width="800" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/3870972/fd22ef18-b88f-48b9-82f2-b40c2166d5d5">

**Comment by FrederLu** [comment] 2023-08-23 02:05
>Duplicate abnormal data appears on the transaction details page.
https://pudge.explorer.nervos.org/transaction/0xaf6690becc7e7f6981322cc73f5d3834728789de194888de3e560290c38cbc7e

The detailed steps are to directly enter the transaction details page of the home page to check the abnormal situation. It's also unusual to jump directly from a link posted in a question.

https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b398bd40-5e5a-4eba-8d8b-7721cd9af28e

**Comment by zhangyouxin** [comment] 2023-08-23 02:19
weird.. here is how it shows on my machine:
https://github.com/Magickbase/ckb-explorer-public-issues/assets/3870972/5b88ae96-7fe6-4c78-8bac-f8a89da8f3f0

I wonder if it is because of some chrome extension.. can you try it under incognito mode?

**Comment by FrederLu** [comment] 2023-08-23 02:32
> weird.. here is how it shows on my machine: https://github.com/Magickbase/ckb-explorer-public-issues/assets/3870972/5b88ae96-7fe6-4c78-8bac-f8a89da8f3f0
> 
> I wonder if it is because of some chrome extension.. can you try it under incognito mode?

Chrome does not use other plug-ins, and has been using the incognito mode. It's just that the version is not the latest `Version 103.0.5060.114 (official release) (arm64)`.

**Comment by zhangyouxin** [comment] 2023-08-23 03:35
> > weird.. here is how it shows on my machine: https://github.com/Magickbase/ckb-explorer-public-issues/assets/3870972/5b88ae96-7fe6-4c78-8bac-f8a89da8f3f0
> > I wonder if it is because of some chrome extension.. can you try it under incognito mode?
> 
> Chrome does not use other plug-ins, and has been using the incognito mode. It's just that the version is not the latest `Version 103.0.5060.114 (official release) (arm64)`.

The reason is that there are two titles for desktop and mobile layout, and the logic to display which title is decided by media query, the current query does not fit old version chrome. 
https://github.com/Magickbase/ckb-explorer-frontend/blob/develop/src/pages/Transaction/TransactionCellList/styled.tsx#L88-L90

**Comment by FrederLu** [comment] 2023-08-23 06:25
> > > weird.. here is how it shows on my machine: https://github.com/Magickbase/ckb-explorer-public-issues/assets/3870972/5b88ae96-7fe6-4c78-8bac-f8a89da8f3f0
> > > I wonder if it is because of some chrome extension.. can you try it under incognito mode?
> > 
> > 
> > Chrome does not use other plug-ins, and has been using the incognito mode. It's just that the version is not the latest `Version 103.0.5060.114 (official release) (arm64)`.
> 
> The reason is that there are two titles for desktop and mobile layout, and the logic to display which title is decided by media query, the current query does not fit old version chrome. https://github.com/Magickbase/ckb-explorer-frontend/blob/develop/src/pages/Transaction/TransactionCellList/styled.tsx#L88-L90

The same is true for browsing with safari, and users will notice similar issues if they use the same browser as me.
<img width="1323" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7df07083-be11-439f-a7c8-c5ff967b0356">

**Comment by zhangyouxin** [comment] 2023-08-23 06:56
will be resolved by https://github.com/Magickbase/ckb-explorer-frontend/pull/52

**Closed** 2023-08-24 06:48 UTC
Labels: bug
